// frozen_string_literal: true
//  Project Euler exercises - Problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
// first 10 terms will be:
//  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
// even-valued terms.
const print = (arg) => console.log(arg);
const limit = 4000000;
let a = 1;
let b = 1;
let next_f = (a + b);
let sum = 0;
while (next_f < limit){
    sum += next_f;
    a = next_f + b;
    b = next_f + a;
    next_f = a + b;
}
print(sum);
